name: CD
on: 
  push:
    branches: [main]
jobs:
  build: 
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      
      - name: build image and push on dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: eullercristian
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eullercristian/argocd-nestjs
          tag: ${{ github.sha }}, latest 